# SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: false
contact_links:
  - name: Bug report
    url: https://github.com/steven-sheehy/hiero-mirror-node/issues
    about: Create a report to help us improve
  - name: Feature
    url: https://github.com/steven-sheehy/hiero-mirror-node/issues
    about: Suggest an idea for this project
  - name: Report a security vulnerability
    url: https://github.com/steven-sheehy/hiero-mirror-node/security/policy
    about: Please review our security policy for more details
